### ISSUE TITLE
Missing countries, e.g. China, Hong Kong

### ISSUE THREAD

**Issue by hlcny** [covid19datahub/R#1]
Hi, 
This is a very promising package. However, x <- covid19() returns no data for China, or Hong Kong...is this intentional (there may be other missing countries, but I haven't checked)?

**Comment by mschrein** [comment]
Hi,
I experienced the same problem. Another quite significant country that is missing is Australia.

**Comment by eguidotti** [comment]
Hi @hlcny and @mschrein, sorry for the late reply.
Australia has been implemented, China is still missing unfortunately.
If you think you might be able to help please have a look at [this issue](https://github.com/covid19datahub/COVID19/issues/75)
Thanks!
