### ISSUE TITLE
No data from the 10/28

### ISSUE THREAD

**Issue by LLanero077** [covid19datahub/R#12]
I don't see any data from the 10/28? Maybe things are not updating correctly from my end, but I just want to make sure...

**Comment by eguidotti** [comment]
Hi @LLanero077, I just tried all the 3 levels and they seem up-to-date as of 11/03. Which country are you looking at?

**Comment by LLanero077** [comment]
Hi sorry I should have mentioned before but I'm looking the United Kingdom

**Comment by eguidotti** [comment]
Thanks! I checked and the data are missing indeed. It seems that the [UK Open Data API](https://coronavirus.data.gov.uk/details/developers-guide/main-api) is experiencing some downtime lately. I'll update this post when the data are back

**Comment by eguidotti** [comment]
The data are back and a new version of this package will be released between 15-18 Novermber 2021. [See the changelog](https://covid19datahub.io/news/index.html)
