### ISSUE TITLE
Warning message for dplyr 1.0.0

### ISSUE THREAD

**Issue by yuanzhouIR** [covid19datahub/R#2]
After updating the dplyr package to version 1.0.0, I got the following warning message when running `covid19("US", level = 2, verbose = FALSE)`.

> Warning message:
The `keep` argument of `group_map()` is deprecated as of dplyr 1.0.0.
Please use the `.keep` argument instead.

The results turned to be no problem. However, would you please fix this when updating this package?

**Comment by eguidotti** [comment]
Hi @yuanzhouIR, sorry for the late reply.
You are 100% right, this should be already fixed in the development version. It should be uploaded on CRAN soon.
```R
remotes::install_github("covid19datahub/R")
```
