### ISSUE TITLE
Required R Version

### ISSUE THREAD

**Issue by jaynal83** [covid19datahub/R#3]
In the package documentation it is mentioned that R versions 2.10 or higher would work. I am trying to install on R 3.4.3 and getting message that required version should be 3.5.0. Am I missing something?

**Comment by eguidotti** [comment]
Hi @jaynal83, sorry for the late reply.
Are you trying the package on CRAN? Unfortunately there was a bug in the DESCRIPTION.
Can you try to install the development version and let me know if this works?
```R
remotes::install_github("covid19datahub/R")
```
Thanks!

**Comment by eguidotti** [comment]
Should be fixed in the latest CRAN release v2.2.0
