### ISSUE TITLE
Data not current

### ISSUE THREAD

**Issue by enricoschumann** [covid19datahub/R#4]
Hi,

the data pulled today (26 June) does not seem to be current:

```r
    library("COVID19")
    x <- covid19(level = 1)
    max(x$date)
    ## [1] "2020-06-24"
```

What am I doing wrong? Many thanks for looking into this.

**Comment by eguidotti** [comment]
Hi @enricoschumann, sorry for the late reply.
This should be fixed now. See https://github.com/covid19datahub/COVID19/issues/84
Thanks!
