### ISSUE TITLE
Data has not been updated

### ISSUE THREAD

**Issue by epatterson573** [covid19datahub/R#7]
Hi,

The level-3 COVID data pulled today (9/1) using R is not updated. The data for 8/31 and 8/30 are the same.

Thanks.

**Comment by eguidotti** [comment]
Hi @epatterson573, thanks for the message.
Actually the data seem up to date. For example, level 3 for Italy has already the data for 9/1. Level 3 for US is not there for today 9/1 as the data are not available yet from the provider (see https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv). The data for 8/31 and 8/30 are not the same, e.g. there is some differences among the US counties.
Am I missing something?

**Comment by epatterson573** [comment]
It is working for me now, thank you.
