### ISSUE TITLE
Incomplete data: getting 35 countries with bare `covid19()`

### ISSUE THREAD

**Issue by llinfeng** [covid19datahub/R#8]
Please advise how to get a more comprehensive record than the following:
![image](https://user-images.githubusercontent.com/5890407/93835593-bfdf8680-fc4d-11ea-9b8a-55119534cfcb.png)

Simple code for replication:
```
library(COVID19)
x <- covid19()
unique(x$administrative_area_level_1)
```
The dataframe `x` has 7750 observations, with 35 unique countries.

**Comment by eguidotti** [comment]
Hi @llinfeng, thanks for your message.
Make sure to use the CRAN version of the package:
```R
install.packages("COVID19")
```
I'm able to download correctly all 196 countries. Your code is correct:
```R
library(COVID19)
x <- covid19()
unique(x$id)
```

**Comment by llinfeng** [comment]
I don't recall having done anything fancy about installation and confirm I was using `install.packages("COVID19")` to install. I assume what I was reporting is a temporary problem? Back then, the simple code snippet does replicate on all computers I have.

Now, I can no longer reproduce the incomplete dataframe using `covid19()` anymore. Thank you for your timely reply!
